FROM  jenkins/jenkins

# 下載 sshpass 建置 sshkey
USER root
COPY start.sh /start.sh
RUN apt-get update && apt-get install -y vim ssh sshpass
RUN mkdir -p ~/.ssh
RUN ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa
RUN curl https://cli-assets.heroku.com/install.sh | sh && heroku plugins:install java
ENTRYPOINT ["/start.sh"]    
CMD ["/sbin/tini","--","/usr/local/bin/jenkins.sh"]
# ENTRYPOINT ["sh","-c","sh /start.sh; /sbin/tini -- /usr/local/bin/jenkins.sh"]

